"""add_place_reviews

Revision ID: 5fe6c16c6978
Revises: 8d6bab21bc7a
Create Date: 2026-05-02 11:55:43.033230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe6c16c6978'
down_revision: Union[str, Sequence[str], None] = '8d6bab21bc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_review_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_data_id'], ['place_raw_data.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_place_reviews_place_id', 'place_reviews', ['place_id'], unique=False)
    op.create_index('uq_place_reviews_place_provider_ext_id', 'place_reviews', ['place_id', 'provider', 'external_review_id'], unique=True, postgresql_where=sa.text('external_review_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_place_reviews_place_provider_ext_id', table_name='place_reviews', postgresql_where=sa.text('external_review_id IS NOT NULL'))
    op.drop_index('ix_place_reviews_place_id', table_name='place_reviews')
    op.drop_table('place_reviews')
    # ### end Alembic commands ###
